### ISSUE TITLE
Unable to locate executable file: curl.

### ISSUE THREAD

**Issue by tabbi89-jobox** [Legion2/swagger-ui-action#484]
```
Warning: Unexpected input(s) 'GITHUB_TOKEN', valid inputs are ['output', 'version', 'spec-file', 'spec-url', 'swagger-config-file', 'swagger-config-url']
Run Legion[2](XXX#step:11:2)/swagger-ui-action@v1
/usr/bin/docker exec  XXX sh -c "cat /etc/*release | grep ^ID"
Configuration: {
  "configMode": "specFile",
  "specFile": "swagger.json",
  "specUrl": "",
  "swaggerConfigFile": "",
  "swaggerConfigUrl": "",
  "swaggerUIVersion": "^3.0.0",
  "outputPath": "swagger-ui"
}
Swagger UI version: v3.52.5
Error: Error: Unable to locate executable file: curl. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

Job runs on ubuntu

**Comment by Legion2** [comment]
Can you please provide the action yaml definition of this job

**Comment by tabbi89-jobox** [comment]
```
- name: Generate Swagger UI
              uses: Legion2/swagger-ui-action@v1
              with:
                output: swagger-ui
                spec-file: swagger.json
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: swagger-ui
```
